Проверьте работу на примере выполнения любой печати строки командой print(‘hi’)


In [ ]:
print('hi')

hi


a. Импортируйте библиотеку NumPy

In [ ]:
import numpy as np
print('Библиотека успешно добавлена')

Библиотека успешно добавлена


b. Создайте массив из 10 нулей

In [ ]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


c. Создать массив из 10 единиц

In [ ]:
a=np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


d. Создать массив из 10 пятерок


In [ ]:
a=np.zeros(10)
a[:]=5
print(a)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


e. Создать массив из целых чисел от 10 до 50

In [ ]:
a=np.arange(10,51)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


f. Создать массив из четных чисел от 10 до 50

In [ ]:
a=np.arange(10,51,2)
print(a)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


g. Создать матрицу 3х3 с числами от 0 до 8

In [ ]:
a=np.arange(0,9)
a=a.reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


h. Создать единичную матрицу 3x3

In [ ]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


i. Используйте NumPy для генерации случайного числа от 0 до 1

In [ ]:
a=np.random.rand()
print(a)

0.9026588927714055


j. Используйте NumPy для генерации массива из 25 случайных чисел, взятых из стандартного нормального распределения

In [ ]:
a=np.random.randn(25)
print(a)

[-0.94473253 -1.91536009  1.28845912 -0.02691373 -1.14269974 -1.25302366
 -1.24407606 -0.79190306 -0.58363757  0.58684435  0.05315929 -0.80840947
  1.12808221  0.60020685  1.21177489  0.48633255  0.59953942 -0.19056492
  1.60806754 -1.33404279  0.54272551  1.46186644 -0.11117097  0.16962572
  1.00031405]


k. Создайте следующую матрицу используя функции библиотеки NumPy

In [ ]:
a=np.linspace(0.01,1,100)
a=np.array(a)
a=a.reshape(10,10)
print(a)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


l. Дана стартовая матрица

In [ ]:
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


Необходимо написать код, который вернет следующую матрицу из стартовой

In [ ]:
a=mat[2:,1:]
print(a)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


m. Написать код обращения к элементу который вернет значение 20 из стартовой матрицы задачи l.

In [ ]:
a=mat[3,4]
print(a)

20


n. Написать код к стартовой матрице задачи l, который воспроизводит вывод, показанный ниже

In [ ]:
a=mat[:3,1]
a=a.reshape(1,3)
print(a)

[[ 2  7 12]]


o. Написать код к стартовой матрице задачи l, который воспроизводит вывод, показанный ниже

In [ ]:
a=mat[4,:]
print(a)

[21 22 23 24 25]


p. Написать код к стартовой матрице задачи l, который воспроизводит вывод, показанный ниже

In [ ]:
a=mat[3:,:]
print(a)

[[16 17 18 19 20]
 [21 22 23 24 25]]


q. Получить сумму всех значений в стартовой матрице mat

In [ ]:
a=mat.sum()
print(a)

325


r. Получить стандартное отклонение в стартовой матрице mat

In [ ]:
a=mat.std()
print(a)

7.211102550927978


s. Получить сумму значений в колонках в стартовой матрице mat

In [ ]:
a=mat.sum(axis=0)
print(a)

[55 60 65 70 75]
